version: '3.5'

services:

  notesfrontend:
    container_name: notesfrontend  
    command: "npm start"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
